"""从 settings.yaml 生成配置项参考文档。

手写的配置参考会立刻过时——2500 行配置，改一处文档就落后一处。
这里从源头导出，`pnpm build` 之后跑一次即可保证与实现一致。

    python scripts/gen-settings-reference.py            # docs/SETTINGS.md
    python scripts/gen-settings-reference.py --lang en  # docs/SETTINGS.en.md

英文版读的是 i18n-settings/settings.en.yaml——发英文包时它就是包内的 settings.yaml，
所以英文参考不是翻译中文参考，而是同样从源头导出。两份配置的分组与字段顺序必须一致，
生成时会校验；对不上说明有一侧漏改了。
"""

import io
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent

# 控件类型 -> 人话
KIND = {
    "text": "文本",
    "textarea": "多行文本",
    "number": "数字",
    "switch": "开关",
    "radio": "单选",
    "select": "下拉",
    "checkbox": "多选",
    "color": "颜色",
    "code": "代码",
    "attachment": "附件",
    "attachmentInput": "附件",
    "array": "对象数组",
    "list": "列表",
    "iconify": "图标",
    "menuSelect": "菜单选择",
    "menuCheckbox": "菜单多选",
    "menuRadio": "菜单单选",
    "categorySelect": "分类选择",
    "tagSelect": "标签选择",
    "postSelect": "文章选择",
    "singlePageSelect": "独立页选择",
    "secret": "凭据",
    "group": "分组",
    "repeater": "重复项",
}

KIND_EN = {
    "text": "text",
    "textarea": "textarea",
    "number": "number",
    "switch": "switch",
    "radio": "radio",
    "select": "select",
    "checkbox": "checkbox",
    "color": "color",
    "code": "code",
    "attachment": "attachment",
    "attachmentInput": "attachment",
    "array": "object array",
    "list": "list",
    "iconify": "icon",
    "menuSelect": "menu select",
    "menuCheckbox": "menu checkbox",
    "menuRadio": "menu radio",
    "categorySelect": "category select",
    "tagSelect": "tag select",
    "postSelect": "post select",
    "singlePageSelect": "single page select",
    "secret": "secret",
    "group": "group",
    "repeater": "repeater",
}

# 每种语言的：源文件、输出文件、控件类型表、以及文档里的固定文案
LANGS = {
    "zh": {
        "source": "settings.yaml",
        "out": "docs/SETTINGS.md",
        "kinds": KIND,
        "title": "配置项参考",
        "note": (
            "> 本文件由 `scripts/gen-settings-reference.py` 从 `settings.yaml` 生成，请勿手改。\n"
            "> 改了配置就重新生成，这样它不会和实现脱节。\n\n"
        ),
        "summary": "共 {groups} 个分组、{items} 个配置项。\n\n",
        "index_head": "| 分组 | 标签 | 配置项数 |\n| --- | --- | --- |\n",
        "access": "模板中访问：`theme.config.{group}.<配置项名>`\n\n",
        "table_head": "| 配置项 | 类型 | 标签 | 默认值 | 说明 |\n| --- | --- | --- | --- | --- |\n",
        "cond": "（仅当 `{cond}` 时显示）",
        # 说明列的截断长度。中文一个字顶英文两三个字母，所以两边不是同一个数。
        "help_max": 120,
        "on": "开",
        "off": "关",
        "done": "已生成 {out}：{groups} 个分组、{items} 个配置项",
    },
    "en": {
        "source": "i18n-settings/settings.en.yaml",
        "out": "docs/SETTINGS.en.md",
        "kinds": KIND_EN,
        "title": "Settings reference",
        "note": (
            "> Generated by `scripts/gen-settings-reference.py` from"
            " `i18n-settings/settings.en.yaml` — do not edit by hand.\n"
            "> That file is what ships as `settings.yaml` inside the English package, so this\n"
            "> reference is exported from the source rather than translated from the Chinese one.\n\n"
        ),
        "summary": "{groups} groups, {items} settings.\n\n",
        "index_head": "| Group | Label | Settings |\n| --- | --- | --- |\n",
        "access": "Access in templates: `theme.config.{group}.<setting name>`\n\n",
        "table_head": (
            "| Setting | Type | Label | Default | Description |\n| --- | --- | --- | --- | --- |\n"
        ),
        "cond": " (shown only when `{cond}`)",
        "help_max": 200,
        "on": "on",
        "off": "off",
        "done": "wrote {out}: {groups} groups, {items} settings",
    },
}


def as_text(v: object) -> str:
    """help / label 可能是 FormKit 的条件式 {if, then, else}，把字符串分支摊平。"""
    if v is None:
        return ""
    if isinstance(v, str):
        return v
    if isinstance(v, dict):
        parts = [as_text(v[k]) for k in ("then", "else") if k in v]
        return " / ".join(p for p in parts if p)
    if isinstance(v, list):
        return " / ".join(filter(None, (as_text(x) for x in v)))
    return str(v)


def fmt_default(v: object, lang: dict) -> str:
    if v is None or v == "":
        return "—"
    if isinstance(v, bool):
        return lang["on"] if v else lang["off"]
    if isinstance(v, (list, dict)):
        return "—" if not v else f"`{v}`"
    s = str(v)
    return f"`{s}`" if len(s) <= 40 else f"`{s[:37]}…`"


def walk(node, depth=0, out=None):
    """收集 (深度，字段定义)。array/list 的子项缩进一级。"""
    if out is None:
        out = []
    if isinstance(node, dict):
        if node.get("$formkit") and node.get("name"):
            out.append((depth, node))
            for child in node.get("children") or []:
                walk(child, depth + 1, out)
            return out
        for v in node.values():
            walk(v, depth, out)
    elif isinstance(node, list):
        for v in node:
            walk(v, depth, out)
    return out


def render(lang: dict) -> tuple[str, int, int]:
    doc = yaml.safe_load(io.open(ROOT / lang["source"], encoding="utf-8"))
    forms = doc["spec"]["forms"]

    buf: list[str] = []
    w = buf.append
    w(f"# {lang['title']}\n\n")
    w(lang["note"])
    # 整文件豁免 lint：这是导出产物，不应被 --fix 改写。
    # 只关 MD013 不够——MD034 会把帮助文案里的裸 URL 自动加尖括号，
    # 中文标点没有空格分隔，会被一起裹进链接里，把内容改坏。
    # （autocorrect 是另一个工具，它按 .autocorrectignore 跳过本文件。）
    w("<!-- markdownlint-disable -->\n\n")

    total = sum(len(walk(f)) for f in forms)
    w(lang["summary"].format(groups=len(forms), items=total))

    w(lang["index_head"])
    for f in forms:
        w(f"| `{f['group']}` | {f.get('label', '')} | {len(walk(f))} |\n")
    w("\n")

    for f in forms:
        w(f"## {f.get('label', f['group'])}\n\n")
        w(lang["access"].format(group=f["group"]))
        w(lang["table_head"])
        for depth, n in walk(f):
            indent = "└ " * min(depth, 1) if depth else ""
            kind = lang["kinds"].get(n.get("$formkit"), n.get("$formkit", ""))
            label = as_text(n.get("label")).replace("|", "\\|")
            help_ = as_text(n.get("help")).replace("|", "\\|").replace("\n", " ")
            cond = n.get("if")
            if cond:
                c = str(cond).replace("|", "\\|")
                help_ = (help_ + lang["cond"].format(cond=c)).strip()
            if len(help_) > lang["help_max"]:
                help_ = help_[: lang["help_max"] - 3] + "…"
            w(
                f"| {indent}`{n['name']}` | {kind} | {label} | "
                f"{fmt_default(n.get('value'), lang)} | {help_} |\n"
            )
        w("\n")

    return "".join(buf), len(forms), total


def check_parity() -> None:
    """两份 settings 的分组与字段必须一一对应，否则英文包会漏配置项。

    这是唯一能自动发现「改了 settings.yaml 忘了改 settings.en.yaml」的地方——
    Halo 不会校验，装了英文包才会看到少一个开关。
    """
    names = {}
    for key in ("zh", "en"):
        doc = yaml.safe_load(io.open(ROOT / LANGS[key]["source"], encoding="utf-8"))
        names[key] = [
            (f["group"], n["name"]) for f in doc["spec"]["forms"] for _, n in walk(f)
        ]
    if names["zh"] != names["en"]:
        only_zh = [x for x in names["zh"] if x not in set(names["en"])]
        only_en = [x for x in names["en"] if x not in set(names["zh"])]
        detail = ""
        if only_zh:
            detail += f"\n  仅中文有：{only_zh[:10]}"
        if only_en:
            detail += f"\n  仅英文有：{only_en[:10]}"
        if not detail:
            detail = "\n  字段集合相同但顺序不同"
        raise SystemExit(
            f"settings.yaml 与 i18n-settings/settings.en.yaml 不同步：{detail}"
        )


def main() -> None:
    args = sys.argv[1:]
    lang_key = "zh"
    if args:
        if args[0] == "--lang" and len(args) > 1:
            lang_key = args[1]
        elif args[0].startswith("--lang="):
            lang_key = args[0].split("=", 1)[1]
        else:
            raise SystemExit(f"用法：{sys.argv[0]} [--lang zh|en|all]")
    if lang_key not in (*LANGS, "all"):
        raise SystemExit(f"未知语言 {lang_key!r}，可选：{', '.join(LANGS)}, all")

    check_parity()

    for key in LANGS if lang_key == "all" else [lang_key]:
        lang = LANGS[key]
        text, groups, total = render(lang)
        out = ROOT / lang["out"]
        io.open(out, "w", encoding="utf-8", newline="\n").write(text)
        print(
            lang["done"].format(
                out=out.relative_to(ROOT).as_posix(), groups=groups, items=total
            ),
            file=sys.stderr,
        )


if __name__ == "__main__":
    main()
